### ISSUE TITLE
m2 test fails: sleep_tpr < 0.45

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#121]
The m2 test seems to fail with the following error:
```
>       assert sleep_tpr > 0.45
E       AssertionError: assert tensor(0.4073, device='cuda:0') > 0.45
```
Is the tolerance too high? Or should we run it for more epochs?

**Comment by jeff-regier** [comment]
Is this still an issue now that #128 is merged?

**Comment by ismael-mendoza** [comment]
Yes, this is something Bryan is looking into separately. I haven't experimented with the m2 test
