### ISSUE TITLE
Galaxies still get scaled down when too little ptile_padding? 

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#133]
Hello @Runjing-Liu120 , I just wanted to document what I mentioned in the meeting just in case there is a bug. Any suggestions are appreciated. 

If I try `tile_slen=4` & `ptile_padding=3` with this [config file](https://github.com/prob-ml/bliss/blob/master/config/model/basic_sleep_galaxy.yaml) I get images that look like: 

![Screen Shot 2020-11-10 at 20 28 49](https://user-images.githubusercontent.com/11745764/98753901-6c5b0080-2393-11eb-9d30-1f10350ee911.png)

On the other hand with `ptile_padding=5`:

![Screen Shot 2020-11-10 at 20 30 22](https://user-images.githubusercontent.com/11745764/98753965-96142780-2393-11eb-9bcf-b7fe5f10c0e9.png)

It looks like galaxies shrunk? But you mentioned this shouldn't be the case so I'm a bit confused. Again, I'm happy to help resolve this issue if you have any suggestions for where to look. For now I'm just using the bigger `ptile_padding` and going with this

**Comment by Runjing-Liu120** [comment]
yeah that's super odd -- I will take a look at this!
