### ISSUE TITLE
Improve metrics

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#137]
Currently I think the accuracy metrics and the median locs mse metrics can be a bit misleading. It would be much better if we did something like the TPR/PPV metrics Bryan uses or if we matched centers to true centers based on some threshold and we reported the number of correct matches across stars and galaxies.

It will be even better if we could directly use the Metrics provided by pytorch lightning or we created our own Metrics Classes to handle all this.

**Comment by jeff-regier** [comment]
It might be good to move the metrics out of the sdss.py file too at the same time because the aren't specific to SDSS. Maybe plotting and metrics functions could all go in a file called reporting.py?
