### ISSUE TITLE
Use tool.poetry.scripts rather than having a bin directory

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#165]
Rather than having our executable scripts (e.g., `tuning.py`) in the bin directory, it'd be preferable to put them within the `bliss` directory, where they can tested by pytest. Poetry has a way to add them to the path:
https://python-poetry.org/docs/pyproject/#scripts

This way, the current working directory does not need to be `bliss/bin` in order for the scripts to work. We may avoid a lot of tedious path issues by doing it this way.

**Comment by ZachariahPang** [comment]
It has to be run in ./bin mainly for saving the best hyper parameter. I didn't find an easy way to reliably determine the correct path to the Hydra config group dir, so I add that constraint to ensure the best hyper parameter can be saved to the correct location using relative path. But I can change it to run from other dir as well, as long as its path is known beforehand.

Another work around would be saving best hyper parameter to an existing file that's managed by Hydra. This way the script can be run from anywhere without a hard encoded path.

It seems like the second one would more preferable. I can make a PR a bit later.

**Comment by ZachariahPang** [comment]
> Rather than having our executable scripts (e.g., `tuning.py`) in the bin directory, it'd be preferable to put them within the `bliss` directory, where they can tested by pytest. Poetry has a way to add them to the path:
> 
> https://python-poetry.org/docs/pyproject/#scripts
> 
> 
> 
> This way, the current working directory does not need to be `bliss/bin` in order for the scripts to work. We may avoid a lot of tedious path issues by doing it this way.

It has to be run in ./bin mainly for saving the best hyper parameter. I didn't find an easy way to reliably determine the correct path to the Hydra config group dir, so I add that constraint to ensure the best hyper parameter can be saved to the correct location using relative path. But I can change it to run from other dir as well, as long as its path is known beforehand.

Another work around would be saving best hyper parameter to an existing file that's managed by Hydra. This way the script can be run from anywhere without a hard encoded path.

It seems like the second one would more preferable. I can make a PR a bit later.

**Comment by jeff-regier** [comment]
Could you use the `BLISS_HOME` environment variable to find the Hydra config group dir? I think we can assume that the config files will always be in `$BLISS_HOME/config`

**Comment by ZachariahPang** [comment]
I forgot we have that. I'll make a change reflecting this.

**Comment by jeff-regier** [comment]
Thanks. I still like the idea of moving the scripts to within the bliss directory, testing them with pytest, and having `poetry install` automatically create executables that are included in the PATH. But it's less critical if the executables don't have to be run from within `bin`.
