### ISSUE TITLE
create documentation with Sphinx

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#168]
About Sphinx: sphinx-doc.org/en/master/usage/quickstart.html

Let's add the documentation pages to directory called `docs` within the bliss repository.

Here's an example: https://github.com/YosefLab/scvi-tools/tree/master/docs

We'd like to use "autodoc" to generate some of the documentation: https://www.sphinx-doc.org/en/master/usage/quickstart.html#autodoc

Here's what docstrings in the code need to look like to get interpretted correctly by autodoc:
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

**Comment by ZachariahPang** [comment]
Vscode also has this [extention](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) that can automatically generate the correct docstring snippets. Pycharm probably has similar functionality but I'm not familiar with it.

**Comment by ismael-mendoza** [comment]
If possible, I would suggest to use the Google format for docstrings (I find it much more readable than the sphinx default) - and I think there is a sphinx extension that can handle this format: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
