### ISSUE TITLE
"bliss" command line interface (and unit tests)

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#169]
Bliss current installs three executable scripts: train, tune, and generate. I think it'd be better to combine all three of these scripts into a single script called "bliss". The bliss script would take a command as it's first argument: train, tune, or generate. The advantage of this approach is that it bundles together all the different bliss commands, and let's us easily add more.

It would also be good to add basic unit tests for the "train" and "generate" modes, as we're missing them currently.

**Comment by ZachariahPang** [comment]
Would it better to import `train.py`, `tune.py`, and `generate.py` in a file and set that file as the entry point in Poetry? Or would you want those three files cleaned and combined in a single file?

**Comment by jeff-regier** [comment]
Either way seems pretty good
