### ISSUE TITLE
decouple the path to the SDSS data from the path to the bliss config files

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#170]
Currently the SDSS data has to be stored in "$BLISS_HOME/data/sdss". It'd be preferable, I think, to have an environment variable called something like `BLSS_SDSS` that references the directory where SDSS data is staged. That way the data wouldn't have to be stored under "$BLISS_HOME". (It's also possible there's a good way to do this with hydra config files, but the setting would need to be machine specific, so I'm not sure.)

On the GPU server we have a lot more space on the `/data` partition than in our `/home` directories. I've created a directory called `/data/sdss`, added us all to a Linux user group called "bliss", and given the "bliss" group read/write access to that directory. The first use of this new environment variable could be to reference this new directory once the SDSS data has been moved there.

**Comment by jeff-regier** [comment]
@dereklhansen Is the a way hydra can store the location of the SDSS dataset too? Seems like it might be nice not to mix environment variables and hyrda config variables if possible. The thing is, the location of the SDSS dataset can be different on different computers -- traditionally something env variables would be used for

**Comment by dereklhansen** [comment]
Since this is something meant to be hardcoded to one place, we can just put it here:

https://github.com/prob-ml/bliss/blob/7654eb9734efaa2e798cd5877a09ecaaae22a35f/config/config.yaml#L19-L21

**Comment by jeff-regier** [comment]
Nice
