### ISSUE TITLE
bliss predict mode

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#172]
Following #169, we'll have an executable script called `bliss` that will take a mode of operation as it's first argument. At first, these modes are just `train`, `tune`, and `generate`. I propose adding a forth mode: `predict`. From the command line, it might be called like this
```
$ poetry shell
$ bliss predict sdss 3900 6 299
```
Here the second argument, "sdss", specifies the data source is SDSS. Following #170, bliss will know where to look for SDSS data. The remaining three fields specify which run, camcol (camera column), and field from SDSS to process. Bliss would load this data using the `SloanDigitalSkySurvey` class and run our inference routines.

Eventually, it would be nice to specify regions of sky to process as a bounding box of WCS coordinates, but that's beyond the scope of this issue.

The output from `bliss predict` would be variational distribution for the image.

**Comment by ZachariahPang** [comment]
There seems to be no easy way to incorporate positional cli argument with Hydra. Hydra takes over `argparse.ArgumentParser` so we can't use the built-in argparse to handle the positional argument along with Hydra. Hydra also doesn't support positional arguments for now. More info on https://github.com/facebookresearch/hydra/issues/215#issuecomment-590117564
https://github.com/facebookresearch/hydra/issues/446
https://github.com/facebookresearch/hydra/issues/443

The closest thing might be
```{bash}
poetry shell
bliss mode=predict data=sdss ...
```
If this is acceptable, I can finish #169 with the above command pattern.

**Comment by jeff-regier** [comment]
Yes, that's fine. Even better perhaps. Thanks for working on this issue.
