### ISSUE TITLE
Test m2 can fail in GPU

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#174]
I just ran the master branch tests (before my most recent merge) in the GPU and I noticed that `test_m2.py` and `test_wake.py` failed: 

```
>       assert sleep_ppv > 0.4
E       AssertionError: assert tensor(0.3926, device='cuda:0') > 0.4

test_m2.py:64: AssertionError
```

Just wanted to make sure with @Runjing-Liu120 if this could be a problem or not?  Thanks!

**Comment by Runjing-Liu120** [comment]
Yeah the first one isn't too concerning for me ... maybe just a random fluke? I have to look into the second one though -- there' we are checking that the wake-trained model has at is better log-likelihood than the initial guess (by half). It seems that the trained model got worse?

**Comment by jeff-regier** [comment]
Getting the metrics working (#137 & #164) may be more urgent than fixing the wake phase tests for now since Ziteng's work depends on the metrics

**Comment by Runjing-Liu120** [comment]
I was trying to fix this issue just now -- it seems that the tests pass most of the time, except for an occasional bad run. 

I was trying to set a seed to avoid this bad behavior, but things still seem to be non-deterministic. I tried calling 

```
pytorch_lightning.trainer.seed.seed_everything(seed=None)
```
at the top, but that didn't seem to work

**Comment by ZachariahPang** [comment]
> I was trying to fix this issue just now -- it seems that the tests pass most of the time, except for an occasional bad run.
> 
> I was trying to set a seed to avoid this bad behavior, but things still seem to be non-deterministic. I tried calling
> 
> ```
> pytorch_lightning.trainer.seed_everything(seed=23412)
> ```
> 
> at the top, but that didn't seem to work

Maybe you also need `torch.set_deterministic(True)` or `pytorch_lightning.Trainer(deterministic=True)` as mentioned in https://pytorch.org/docs/stable/notes/randomness.html and https://pytorch-lightning.readthedocs.io/en/latest/trainer.html
