### ISSUE TITLE
Delete .cuda() or .to() calls

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#179]
There are a number of calls to `.to()` in decoder.py, e.g.,
https://github.com/prob-ml/bliss/blob/68657fb8f417c75c41b24f4a5f806b67368c3936/bliss/models/decoder.py#L149

These may be problematic, at least for multi-GPU training, but perhaps just for getting everything on the right device. See
https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#delete-cuda-or-to-calls

**Comment by ZachariahPang** [comment]
This may be a bit harder than I thought. The call to `decoder.py` happens in `__iter__` in `SmilulatedDataset()`. Pytorch-lightning at least, normally generates data batch on cpu and then transfer the batch to gpu before each training step. I searched a bit and couldn't find much information on generating data on gpu natively supported by pl. There are some workaround for this but only for some simple data generation and single gpu training. Ours is fairly complicated. I posted a question on their Slack and I'll keep looking around but this would probably take longer.

**Comment by jeff-regier** [comment]
One option might be to get rid of the `SimulatedDataset` class, and move data generation to the beginning of the `forward` method of the `SleepPhase` class. `SimulatedDataset` was never much like a real dataset---it doesn't have to be loaded from disk or transferred to the GPU.

The only thing ugly about this solution is that `SleepPhase` still needs a dataloader to satisfy pytorch-lightning. If we got rid of `SimulatedDataset`, I think we'd have to create some sort of dummy dataset and dataloader. e.g. `torch.TensorDataset(torch.zeros(50000))`.
