### ISSUE TITLE
warnings due to tune test? 

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#183]
In the latest PR, I saw that running the test in the CI caused a lot of warnings to be thrown related to the `test_tune.py`. 
Below is an excerpt and [here](https://github.com/prob-ml/bliss/runs/1737057512) is the complete version (see`Run Tests`). Do you know why this is happening @zzhaozhe-profolio or @ZachariahPang ? Thanks!

```
tests/test_tune.py::TestTune::test_tune_run
  /home/runner/.cache/pypoetry/virtualenvs/bliss-UE3m6-Ul-py3.8/lib/python3.8/site-packages/aiohttp/payload_streamer.py:57: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def write(self, writer):

tests/test_tune.py::TestTune::test_tune_run
  /home/runner/.cache/pypoetry/virtualenvs/bliss-UE3m6-Ul-py3.8/lib/python3.8/site-packages/aiohttp/payload_streamer.py:68: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def write(self, writer):

tests/test_tune.py::TestTune::test_tune_run
  /home/runner/.cache/pypoetry/virtualenvs/bliss-UE3m6-Ul-py3.8/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-4
  
  Traceback (most recent call last):
```

**Comment by zzhaozhe-profolio** [comment]
We probably need to update aiohttp to fix this: https://github.com/aio-libs/aiohttp/issues/4842

**Comment by ZachariahPang** [comment]
Maybe raised by some recently updated package because I didn't see those in #180 as in https://github.com/prob-ml/bliss/runs/1724460865. I'll check that in detail later.
