### ISSUE TITLE
Document dependency on BLISS_HOME environment variable

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#186]
I tried running the tests on the Linux server and I noticed there needs to be "BLISS_HOME" present in the environment, but I don't see this documented anywhere. Is there a place we could document this?

Alternatively, Hydra comes with some helper functions that can return the absolute path of the original working directory (hydra.utils.get_original_cwd()). This may be useful to avoid hard-coding an absolute path. I don't know how much work this would be to change, however.

**Comment by jeff-regier** [comment]
Good point. I'm not attached to the idea of having a BLISS_HOME environment variable. If there's a way to configure it so that documentation isn't even necessary, that would be ideal

**Comment by jeff-regier** [comment]
Maybe something with the hydra config path?
https://hydra.cc/docs/advanced/search_path

**Comment by dereklhansen** [comment]
I was thinking more along these lines: https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/

But now that I think about it, ```hydra.utils.get_original_cwd()``` would return the directory from which the script was called, which means we'd have to call the scripts from the same working directory. This is something else we'd have to document.

Since poetry seems to automatically register the top-level project in sys.path, the simplest solution might be just to use the `__file__` variable from the bliss module. This will be persistent regardless of the working directory (as long as poetry shell is activated).
```
(bliss-FSmgvuKM-py3.8) [dereklh@deeplearning-01:~/projects/bliss]
$ python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bliss
>>> bliss.__file__
'/home/dereklh/projects/bliss/bliss/__init__.py'
>>> 
(bliss-FSmgvuKM-py3.8) [dereklh@deeplearning-01:~/projects/bliss]
$ cd case_studies/
(bliss-FSmgvuKM-py3.8) [dereklh@deeplearning-01:~/projects/bliss/case_studies]
$ python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bliss
>>> bliss.__file__
'/home/dereklh/projects/bliss/bliss/__init__.py'
```
