### ISSUE TITLE
test_sdss raises warning

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#206]
```
tests/test_sdss.py::TestSDSS::test_sdss
  /home/imendoza/.cache/pypoetry/virtualenvs/bliss-W0ocb7P7-py3.8/lib/python3.8/site-packages/astropy/wcs/wcs.py:513: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0)
    warnings.warn(
```

Hvae you seen this before @jeff-regier or @dereklhansen ? Thanks!

**Comment by jeff-regier** [comment]
Not that one, but I fixed/suppressed another by using the warnings package:
https://github.com/prob-ml/bliss/blob/e49a589d92337822d0370588aad7c932436c9b1c/bliss/datasets/sdss.py#L317-L319

I think that would work for suppressing this one too.

**Comment by ismael-mendoza** [comment]
@dereklhansen  do you know which line of code could be throwing this error?
