### ISSUE TITLE
install fftw3 via pyproject.toml

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#207]
Following #194, we will have galsim as a dependence. It requires a non-pip installable package called `fftw`. Currently I install it in the CI workflow with: 
```
sudo apt-get install libfftw3-dev
```

@jeff-regier  mentioned it should be installable via the pyproject.toml via its [conda wheel](https://anaconda.org/eumetsat/fftw3). If anybody has ideas for how to do this, that would be great.

**Comment by jeff-regier** [comment]
It seems fine to install it with apt. Perhaps we should add something to the readme about to install bliss, since it's a bit more complicated than typing `poetry install` now

**Comment by ismael-mendoza** [comment]
Great, I added this to the readme in my most recent PR
