### ISSUE TITLE
installing dependencies on CI is slow

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#208]
Following #194 adding galsim as a dependency slowed down the CI dependency installation quite a bit (from 2m to 7m). It might be related to #207 and we can probably also improve by caching pip? Although not sure how that works with poetry.

**Comment by jeff-regier** [comment]
Continuous integration over at galsim takes 18 minutes:
https://travis-ci.org/github/GalSim-developers/GalSim/jobs/743005753/config

There might not be a way to speed this up

**Comment by ismael-mendoza** [comment]
Hmm I was looking at the CI run [here](https://github.com/GalSim-developers/GalSim/runs/1841153399?check_suite_focus=true). It seems like installing their dependencies only takes like (<1 min). So I'm hoping we can still speed-up somehow, in any case this is not too urgent so we can come back to this later. But here is a github action that seems to be able to cache poetry: https://github.com/marketplace/actions/setup-poetry

**Comment by jeff-regier** [comment]
Good pont, I guess it's possible
