### ISSUE TITLE
Option to rebuild checkpointed sleep model in predict.py

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#224]
After merging in the new predict code on #218, the test for predict.py fails because it is trying to load a checkpoint of the model. 

https://github.com/prob-ml/bliss/blob/24c2a8bbf3dadbec4d96b2f74a5aab0f013930cd/bliss/predict.py#L16

This fails since I have changed some of the attributes of the decoder. Is there a way to rebuild this checkpoint?

@ismael-mendoza

**Comment by ismael-mendoza** [comment]
Hi @dereklhansen, thanks for the question! Yes I actually did not add an option to `predict.py` to do this because you can use `train.py` to recreate the checkpoint. Here is the command:

```
poetry run bliss mode="train" model="sleep_galaxy_measure_stars1" dataset="default" paths.output="path/to/output/directory" gpus=[2] optimizer.params.lr=1e-4 training.n_epochs=201 training.trainer.checkpoint_callback=True
```

**Comment by dereklhansen** [comment]
Thanks Ismael - this is very helpful
