### ISSUE TITLE
Use of self.forward()

### ISSUE THREAD

**Issue by ZachariahPang** [prob-ml/bliss#248]
I just notice this and I'm not sure if it's intentional, but should we use  `self()` instead of `self.forward()`? I think `self()` is the recommended way to do a forward pass since `__call__` applies hooks and other stuff besides just calling `self.forward()`. This might cause some subtle bugs later on.
https://github.com/prob-ml/bliss/blob/f18dd87cfab26bf0ef1b980db340179020977cad/bliss/models/encoder.py#L583
https://github.com/prob-ml/bliss/blob/f18dd87cfab26bf0ef1b980db340179020977cad/bliss/wake.py#L88

**Comment by jeff-regier** [comment]
I prefer that we just have one way to do it throughout the codebase. Calling `self(img)` seems more idiomatic.
