### ISSUE TITLE
Problems with latest measurements on SDSS chunk

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#261]
See latest results here #258 and below

![image](https://user-images.githubusercontent.com/11745764/120654779-ff52a980-c44f-11eb-8092-e16e1806adff.png)

## Questions

* We miss 3 galaxies on the bottom-right, is that OK? 
* What about the second overlapping galaxy? at the bottom-right? 
* The predicted star on the bottom-left looks smaller. Could the PSF model be off? Or is it just the flux miscalculation
* Shouldn't all stars look the same? The star on the top-left looks really different! I don't think there is hope for that one. 
* Why do we mis-classify the star on the top-right (looks easy and similar to the bottom-left one) Check if it was borderline?
* Why do we mis-measure the large elliptical galaxy in the bottom-left? (see #260)

## Next steps
- [ ] Identify which sources are below detection threshold by looking at catalog (remember, the catalog is on the coadds but we measure on the single frame)
- [ ] Try to simulate the SDSS chunk using synthetic data (looking at photo catalog) and take a look at the differences (identify model misfits)
- [ ] Investigate whether noise model could be incorrect. 
- [x] Investigate whether PSF model could be incorrect. 
- [ ] Train on synthetic data that has parameters really close to this chunk
- [x] Take another careful look into Bryans [notebook](https://github.com/prob-ml/bliss/blob/bryan-sdss-experiment/case_studies/sdss_galaxies_bl/sleepnet_single_tile_results.ipynb), most of the results are what I would expect though.
- [ ] Do we have a problem classifying star vs galaxies? If so, that should be a separate github issue - investigate photo [classification](https://www.sdss.org/dr12/algorithms/classify/). How do people do it usually? Take a look at some star magnitudes
- [ ] Investigate issues with large galaxies in #260

**Comment by jeff-regier** [comment]
Hi @ismael-mendoza, Will you update to this issue to reflect the latest results? And perhaps break it up into smaller issues for whatever issues are remaining? Off the top of my head, the ones I can think of are that 1) star fluxes can be inaccurate, and 2) those two galaxies in the lower left aren't getting deblended (perhaps because the lower right one isn't detected?)

**Comment by ismael-mendoza** [comment]
Yes! That's a great idea, let me close this one and create a couple of smaller issues
