### ISSUE TITLE
Using PSF real image rather than 6 parameter model degrades sleep performance

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#317]
This was surprising to me, following #316 I tested the sleep phase on the PSF image at the center of the stripe-82 frame (obtained from the `psf_at_points` function) and the performance was degraded (the loss that the model converged to wasn't as low as before). To be more specific, the metrics that were related to fluxes all got severely impacted, so there appears to be something off with the flux estimation after this change (most of the other metrics improved a little or stayed the same)

I don't know the reason for this and perhaps this requires a more thorough follow-up investigation. I'm going to probably leave this for now as an issue, address it later, and use whatever works best for BLISS.

**Comment by dereklhansen** [comment]
Closed during meeting
