### ISSUE TITLE
Github action to rebuild documentation

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#340]
I always forget to rebuild the documentation whenever I push, might it be good to have a github action that does it automatically at every push to master?

**Comment by dereklhansen** [comment]
I agree that would be good; I don't know how to do it though

**Comment by dereklhansen** [comment]
This is my git pre-commit hook:

```
╰─$ cat .git/hooks/pre-commit                                                                                                                                                                                                     130 ↵
#!/bin/bash
cd ./docs/docsrc
make clean
make github
cd ..
git add .
```

**Comment by dereklhansen** [comment]
Still an issue

**Comment by dereklhansen** [comment]
I think this can be done as follows:
1. Whenever a commit is made to `master`, build the documentation and force-push to the `docs` branch.
2. Set the Github Pages to follow the `docs` branch.

Step 1 can be achieved with something like this: https://github.com/ad-m/github-push-action
Step 2 should be easy to change from the settings.
