### ISSUE TITLE
KDTrees instead of Hungarian algorithm for matching

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#346]
@jeff-regier mention this idea where for matching objects it might be possible to use KDTrees rather than the Hungarian Algorithm given that locations have spatial structure. Not urgent to implementbut good to keep in mind if we ever want to make the matching faster.

**Comment by jeff-regier** [comment]
Relevant line:
https://github.com/prob-ml/bliss/blob/bd740ea1843010579a81f55cb675f9c39a83cc3f/bliss/reporting.py#L180

**Comment by jeff-regier** [comment]
Addressed by PR #591
