### ISSUE TITLE
combine encoder models into one for prediction

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#352]
In our last meeting, @dereklhansen mentioned that combining the 3 models into one could be beneficial. Currently in `predict.py` we need to manage combining the output of each of the 3 models consistently into a single output, while it feels like it would be better to manage this logic elsewhere i.e. predict.py should just have to call `model.predict()` given a `model`. 

- [ ] Ensure that galaxy parameters returned do not correspond to stars like it's done in `predict.py`

**Comment by jeff-regier** [comment]
Is this issue resolved by one of @dereklhansen's recent PRs?

**Comment by ismael-mendoza** [comment]
I think so specifically with: 

https://github.com/prob-ml/bliss/blob/bedc82ad812cb0f7faebf62625b3d3f7304e0782/bliss/encoder.py#L16

@dereklhansen please correct me if I'm wrong but I'm closing this issue.
