### ISSUE TITLE
Attribute docstrings for classes should be under class not __init__

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#353]
We also need to create these, which are none existant for most classes I think.

**Comment by jeff-regier** [comment]
It doesn't look this is still an issue. Please re-open it if I'm mistaken (and, ideally, mention which classes need their documentation updated).

**Comment by ismael-mendoza** [comment]
@dereklhansen I think you mentioned it in a meeting sometime ago, do you think this is important to do at some point?
