### ISSUE TITLE
Why does SleepPhase need ImageDecoder as input?

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#359]
One of the key inputs to SleepPhase is the ImageDecoder, but every reference to it in sleep.py and predict.py is either an assertion or used to get a setting (e.g. "n_tiles_per_image"). This is because "ImageDecoder" actually has impact through the "SimulatedDataset" during training.

To avoid duplication and possibly conflicting state by having two "ImageDecoder" objects, I propose eliminating the one that is given as input to SleepPhase.

**Comment by jeff-regier** [comment]
Needed for plotting while training
