### ISSUE TITLE
Incorporate uncertainty in galaxy parameters into predictions

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#363]
This can follow once #339 is merged.

Right now I plan on just using the mean from the galaxy VAE in the predict.py pipeline, since this most closely matches the previous behavior. However, it might be interesting to utilize this uncertainty. For example, when we estimate fluxes, integrating over a few samples would give a better estimate of the posterior mean (and also highlight uncertainty).

**Comment by dereklhansen** [comment]
In #339, we use just one sample from the variational distribution (rather than the mean). With the residual VAE, the MAP estimate from the variational distribution is no longer tractable.

**Comment by dereklhansen** [comment]
Copy-pasting my explanation earlier so I remember to do this
> Right now galaxy_encoder returns a single sample from the variational distribution (and the associated density ratio of that sample) to minimize changes to the rest of the code. I'll likely refactor this in #363 by having the encoder forward method return a "Normal" object (which can be sampled, have the mean and var extracted, etc.)

**Comment by jeff-regier** [comment]
closed by #620
