### ISSUE TITLE
include tutorials in our documentation

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#370]
To help end users to get started with BLISS, let's create tutorials like these:
https://astroalign.readthedocs.io/en/latest/tutorial.html

**Comment by dereklhansen** [comment]
We're probably better off starting from scratch than trying to convert `case_studies`.

**Comment by dereklhansen** [comment]
Maybe we can collect a list of all the workflows we do right now that are worth documenting. 
- [ ] "Galaxy sleep phase training" (i.e. the Makefile in models/) @dereklhansen 
- [ ] Generate predictions on real SDSS image @ismael-mendoza

**Comment by dereklhansen** [comment]
I'm happy to put together the .rst files for Sphinx if @ismael-mendoza can send me a script or notebook for generating predictions on an SDSS chunk

**Comment by jeff-regier** [comment]
On second thought, we probably should complete #378 and #429 before putting a lot of effort into developing tutorials for end users. The BLISS API will likely change a lot until those are done, and BLISS software will only become relevant to a lot of end users once those issues are resolved

**Comment by ismael-mendoza** [comment]
I will upload collab demo notebook for training and predicting the detection encoder

**Comment by jeff-regier** [comment]
closed by #786
