### ISSUE TITLE
Negative flux predictions

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#375]
A noticed that a small number (~0.1%) of galaxies can get predicted with a negative flux. The galaxies for which these happens have _very_ low flux to the point that we will never detect them. I think we should remove such dim galaxies from the galaxy sample and this would get rid of this issue 

- [ ] increase the `min_flux` in the `sdss_galaxies.yaml` config and rerun

**Comment by jeff-regier** [comment]
Is this still happening? Shouldn't the galaxy autoencoder end with a relu so that its output is always nonnegative (regardless of how it's trained)?

**Comment by ismael-mendoza** [comment]
I'll pin this issue so I don't forget about it because it is definitely important. @dereklhansen can comment more on this since he was the last one to tweak the autoencoder. I suggest we wait until we decide whether we want to keep the autoencoder at all (following the metrics in #425 ) and then we can just check this on the VAE.

**Comment by dereklhansen** [comment]
The decoded image should always be non-negative in both the autoencoder and the VAE:

https://github.com/prob-ml/bliss/blob/02bf153dd87aa6eedf18eacbc0fcce274c2f9b16/bliss/models/galaxy_net.py#L394-L398

**Comment by dereklhansen** [comment]
But we should double-check that the computed "galaxy_fluxes" from #425 are always non-negative (maybe make this a test?)

**Comment by ismael-mendoza** [comment]
Yes definitely a small test would be a good idea
