### ISSUE TITLE
get_full_params_from_tiles() errors out when "prob_n_sources" in dictionary

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#394]
This bug occurs when "prob_n_sources" is in the dictionary; this is a problem since it is one of the elements in the output of LocationEncoder.max_a_post()

**Comment by dereklhansen** [comment]
The solution is to fix the dimension of "prob_n_sources" to make it consistent with the other tensors

**Comment by ismael-mendoza** [comment]
This is my fault, I introduced this variable thinking it would be helpful but it wasn't. It also doesn't make sense to assign to a particular source (this is related to the bug) so I'm getting rid of it.
