### ISSUE TITLE
Add a script to reproduce data/true_hubble_m2.npz

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#437]
It seems `data/true_hubble_m2.npz` comes from the SDSS catalog, but I don't see the code that produced it. Is there a way we can use the `SloanDigitalSkySurvey' class instead?

@ismael-mendoza @jeff-regier

**Comment by jeff-regier** [comment]
@Runjing-Liu120 will you share the code for this with Derek?

**Comment by jeff-regier** [comment]
It's not so clear from this thread what is left to do. Let's close this issue and open a fresh one if there's a task left to do.

**Comment by ismael-mendoza** [comment]
Isn't this the task that is left to do? @jeff-regier 

> To fix this issue, I will add a script you can run in this repo, to generate this npy file.

**Comment by jeff-regier** [comment]
Ah OK, I may have gotten carried away trying to close issues.
