### ISSUE TITLE
In decoder.render_images, images is NOT equal to var_images

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#438]
We generally operate under the assumption that images==var_images, since that is theoretically justified as a Normal approximation to the Poisson distribution. Thus, I've always found it strange that we render the variance separately from the mean when they should be the same:

https://github.com/prob-ml/bliss/blob/957d5ce840eba1af0120d2ed04f3a416dd151843/bliss/models/decoder.py#L107-L155

In fact, every spot we use "render_images" only uses the mean, except this one line in the galaxy encoder:
https://github.com/prob-ml/bliss/blob/957d5ce840eba1af0120d2ed04f3a416dd151843/bliss/models/galaxy_encoder.py#L136-L145

This is problematic, since I ran `torch.allclose()` on the two images and found they weren't the same when rendering galaxies.
We can see why from this part of the decoder:

https://github.com/prob-ml/bliss/blob/957d5ce840eba1af0120d2ed04f3a416dd151843/bliss/models/decoder.py#L220-L227

**Comment by dereklhansen** [comment]
I think its safe just to return the mean, since we have only been using the mean to generate simulated images anyways:
https://github.com/prob-ml/bliss/blob/957d5ce840eba1af0120d2ed04f3a416dd151843/bliss/models/decoder.py#L169-L180

**Comment by jeff-regier** [comment]
Sounds good
