### ISSUE TITLE
create a dataset of galsim simulated blends

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#455]
For the paper, I will need to generate simulated images of galsim blends that do not come from our decoder in order to evalute BLISS. This should be quite simple, it would just involve drawing `n_galaxies` galaxies from the `SDSSGalaxies` dataset and pasting them in random positions in a ~80x80 postage stamp. It should also return the flux, shapes, and position fo each galaxy so we can compute some metrics

We also need to decide exactly how to tune easy blends vs hard blends. Or if there is a way to change blendedness rate easily. 

This class would be useful generally in the BLISS codebase for evaluating our deblender models on true simulated data.

- [ ] save each galaxy property to a catalog in batches
- [ ] limit max shift so that galaxies are inside the “border padding”
- [ ] no need to include stars
- [ ] specify max number of galaxies

**Comment by dereklhansen** [comment]
Related to #477.

**Comment by ismael-mendoza** [comment]
Related to #501 (could potentially use this dataset)
