### ISSUE TITLE
multiple image transformations for location encoder

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#464]
If the particular image normalization procedure we apply makes such a difference, perhaps we should apply multiple different normalization procedures (e.g., one that subtracts 4 sds, one that subtracts 3.4 sds), stack the normalized images (one channel each), and pass the whole stack to the location autoencoder. It may help to dedicate two input channels to the background and the unnormalized image too, in case the location autoencoder can figure out how to make use of them.

_Originally posted by @jeff-regier in https://github.com/prob-ml/bliss/issues/460#issuecomment-1055559806_

**Comment by dereklhansen** [comment]
I think #474 solves this issue.
