### ISSUE TITLE
Simulate frame from generative model for performance baseline

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#475]
For evaluating our predictive performance, it might be useful to generate an image from our generative model. Then we have an upper bound on the performance we can expect from real data.

**Comment by dereklhansen** [comment]
Related to #455

**Comment by ismael-mendoza** [comment]
Just a note, #455 would actually be images not from our generative model. The dataset I have in mind is more for evaluation and making sure that we can reconstruct galaxy blends that are not generated from our generative model but still from galsim.

**Comment by dereklhansen** [comment]
Closed by #477.
