### ISSUE TITLE
ImagePrior used for galaxy encoder is different from other encoders

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#481]
As you can see in this [config](https://github.com/prob-ml/bliss/blob/master/case_studies/sdss_galaxies/config/training/sdss_galaxy_encoder.yaml) file, I'm using a different `mean_sources` just for the galaxy encoder than for the location and binary encoders. Is it weird that one of the encoders uses a different prior ? My original motivation was to train the galaxy encoder on harder blends but if we want to match SDSS then we should make the prior consistent (not many blends)

What do you think @jeff-regier @dereklhansen ?

**Comment by dereklhansen** [comment]
I think the more important issue is that the rate of `0.03` is far higher than the true SDSS rate. In situations where it's ambiguous, this might be leading the `LocationEncoder` to be too sensitive.

**Comment by dereklhansen** [comment]
Let's not rush to change anything yet, but one thing we could do is set the prior rate to the true rate (e.g. `0.003`). Then, when training, we sample with the higher rate `0.03` and attach importance weights to downplay the significance of the harder blends.

**Comment by dereklhansen** [comment]
I don't think this is an issue, since the galaxy encoder is conditioned on the locations

**Comment by ismael-mendoza** [comment]
Yup, I agree. I think that you can close this after merging #512
