### ISSUE TITLE
Improve generative model of galaxies with a normalizing flow 

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#502]
Have you considered fitting a normalizing flow (alone -- not part of a VAE) as the galaxy model? We could train it on individual galaxies sampled **without Poisson noise** from galsim. The marginal likelihood of the data, p(x), can be optimized directly in this setting, so it may fit really well. The trained flow could then be embedded in the larger bliss generative model, which includes a Poisson conditional likelihood.

_Originally posted by @jeff-regier in https://github.com/prob-ml/bliss/issues/501#issuecomment-1081882196_

**Comment by dereklhansen** [comment]
This isn't a high priority for the current publication, but could be the basis of future work.

**Comment by jeff-regier** [comment]
I'll write down this issue in a notebook of project ideas. I think it's better to keep it there than here since we don't have any immediate plans to work on it.
