### ISSUE TITLE
refactor methods in location_encoder related to index matrices

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#530]
In particular it's a mystery why we need to pad the variational parameters in `location_encoder.py`

```
vpf_padded = F.pad(var_params_flat, (0, len(self.variational_params), 0, 0))
```

My theory is that it's related to "off source" special case indexing, but I need to think about this more.

Related comment: https://github.com/prob-ml/bliss/pull/527#discussion_r846302514

**Comment by jeff-regier** [comment]
Subsumed by #540 . There are a series of related changes that would need to happen to get rid of this line (though I think  `len(self.variational_params)` here can be safely changed to `1`).
