### ISSUE TITLE
Bliss predictions depend on exactly which tiles are used (shift) 

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#549]
After talking to @dereklhansen we realized that BLISS predictions for a given object depend on how tiles are assigned. This was causing the different in detection of the source I presented Wednesday (reproduced below). The only different between the images is that one of them is shifted by 2 pixels respect to the other one, so the tiles produced are different (since 2 is not a multiple of tile_slen). This is enough to make bliss change the probability of detection by 10% and not detect the object in one of these cases which is concerning. 

EDIT: This also drastically shifts the probabilities between the adjacent tiles of the blend. 

![Screen Shot 2022-04-18 at 10 15 14 PM](https://user-images.githubusercontent.com/11745764/163906624-1aa57f1c-f77e-41e4-b6c5-53e3e09bb505.png)

![Screen Shot 2022-04-18 at 10 14 09 PM](https://user-images.githubusercontent.com/11745764/163906522-d7eaa1c6-3638-4090-90ce-435b3cf8582b.png)

**Comment by dereklhansen** [comment]
I wouldn't label this a bug. It's just a fact of the model we're using.

**Comment by ismael-mendoza** [comment]
Here is another striking example with a mild blend (shifted by two pixels again)

![Screen Shot 2022-04-19 at 4 56 20 PM](https://user-images.githubusercontent.com/11745764/164094234-aaf8fed9-d703-411c-b5a1-be8454f12c9d.png)

![Screen Shot 2022-04-19 at 4 56 37 PM](https://user-images.githubusercontent.com/11745764/164094276-720999bb-98d2-4432-b6ab-8e4169d4af08.png)

**Comment by jeff-regier** [comment]
Our location encoder doesn't need to be perfectly invariant to shifts in the input. Perhaps the underlying issue is that the location encoder just isn't accurate enough. I don't recall Bryan having issues like this before with StarNet, but his tiles were smaller (2x2, whereas yours are 4x4, right?) Might reducing the tile size may improve the training/accuracy of the location encoder, and fix these issues?

**Comment by ismael-mendoza** [comment]
> Our location encoder doesn't need to be perfectly invariant to shifts in the input. Perhaps the underlying issue is that the location encoder just isn't accurate enough.

Yes I agree, if the encoder is accurate enough then it doesn't matter that is not shift invariant. 

> I don't recall Bryan having issues like this before with StarNet, but his tiles were smaller (2x2, whereas yours are 4x4, right?) Might reducing the tile size improve the training/accuracy of the location encoder, and fix these issues?

Yes - both me and Derek suspect that if the tiles are smaller this would be less of an issue. So Bryan might not even have noticed this. There are some technical reasons related to how tiles are constructed that prohibits using tile_slen < 4. There is probably a way in which we can bring back the tile_slen = 2 but it would require some work.

**Comment by jeff-regier** [comment]
Is this still an issue after #561?
