### ISSUE TITLE
the maximum a posteriori estimate samples flux?

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#559]
The function `max_a_post` appears to be sampling fluxes, rather than returning a MAP estimate:

https://github.com/prob-ml/bliss/blob/89b26a77ffbad0bc18bd8efcc3b8edf1a693fc5b/bliss/models/location_encoder.py#L277

**Comment by jeff-regier** [comment]
Oh I see, the standard deviation is set to 0. Still, this is a bizarre way to do it.

**Comment by dereklhansen** [comment]
Can you rename this issue to be more actionable?
