### ISSUE TITLE
three tests fail due to AssertionErrors on the GPU

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#563]
When I run `pytest --gpu` (on the master branch, both before and after merging #560), three AssertionErrors are raised:
```
tests/case_studies/sdss_galaxies/test_galaxy_autoencoder.py:56: AssertionError
tests/case_studies/sdss_galaxies/test_location_encoder.py:39: AssertionError
tests/case_studies/sdss_galaxies_vae/test_galaxy_vae.py:71: AssertionError
```

**Comment by jeff-regier** [comment]
If these AssertionError are due to random variation and/or incomplete optimization, we may want to start thinking about different testing strategies. Because the tests are already quite slow and (IIRC) the tolerances are already quite lax. For testing, perhaps we could initialize encoders with pre-trained weights? Or use more simplistic training and testing data (e.g., all stars have the same brightness)?

We may also want to consider having Github CI run pytest both with and without the `--gpu` flag.

**Comment by dereklhansen** [comment]
> We may also want to consider having Github CI run pytest both with and without the `--gpu` flag.

I like this idea, because I never think to run the `--gpu` flag. Is there a way to use Github CI with our GPU server?

**Comment by jeff-regier** [comment]
I have separate server with one GPU for running Github CI tests that is hosted in West Hall. We're already using it for Prayag and Roman's projects. Those are private repos though whereas this one is public, so we may want to be a bit more secure for this one (i.e., launch a new docker instance for each test).
