### ISSUE TITLE
Add typing stubs for rest of imports

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#566]
In #565, I gave an example on how to add typing information for the einops module. Here's the output of mypy indicating the rest of modules that do not have proper typing support:

![image](https://user-images.githubusercontent.com/12701492/164743284-991dba61-28af-4482-8352-3abd06eb0419.png)

We should add as many of these as possible, because the more typing information we give MyPy the better it can spot errors. However, there's a lot of libraries here and it's probably not worth the effort to stub all of them ourselves. Some of the more popular libraries like scipy and matplotlib have third-party stubs available, but I doubt packages like `nflows` do.

**Comment by dereklhansen** [comment]
List of modules:
- [ ] scipy
- [ ] matplotlib
- [ ] astropy
- [ ] galsim
- [ ] tqdm
- [ ] mpl_toolkits
- [ ] sklearn
- [ ] nflows

**Comment by jeff-regier** [comment]
We decided against adding typing stubs for third-party packages other than einops
