### ISSUE TITLE
For LocationEncoder and related, rename `max_a_post()` to `variational_mode()` to be more accurate 

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#571]
Following discussion in #570, it's not accurate to say we are taking the MAP estimate. We are taking the mode of the variational distribution, which is hopefully a good approximation of the true MAP.

**Comment by jeff-regier** [comment]
Perhaps `variational_mode()` rather than `mode()`, to distinguish it from the exact mode of the posterior distribution
