### ISSUE TITLE
Keep number of dimensions consistent throughout LocationEncoder

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#572]
Following discussion in #570, we shouldn't need to flatten/unflatten throughout the LocationEncoder. I see two possibilities:

1. The LocationEncoder keeps the full dimensions throughout (`n_samples x batch_size x n_tiles_h x n_tiles_w x max_sources x D`).
2. The LocationEncoder only operates on padded tiles (`n_samples x n_ptiles x max_sources x D`) throughout.

I'm starting to think Option 2 might be better, because it would make the implementation of LocationEncoder simpler. With this change, methods higher up in the call stack (like `Encoder.max_a_post()` or `.training_step()` from PyTorch Lightning) would be responsible for:
- Creating a valid TileCatalog object with the correct arrangement of tiles (i.e. `"n_ptiles -> batch_size n_tiles_h n_tiles_w"`
- Transforming the input image and background into padded tiles

**Comment by jeff-regier** [comment]
I agree, option 2 seems a bit better, though option 1 has some merits too. Option 2 would get rid of two or three dimensions from many of the tensors used in LocationEncoder, making it a lot easier to understand.
