### ISSUE TITLE
ensure that photo catalog on frame uses detections for only 'r' band

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#580]

**Comment by jeff-regier** [comment]
We may not want to filter detections based on `thing_id` here:
https://github.com/prob-ml/bliss/blob/fa510f369700dc413819913e8788d06fcaf4001c/bliss/datasets/sdss.py#L145-L146

[This page](https://www.sdss.org/dr12/algorithms/resolve/, especially the "toy example" section, illustrates how the `thing_id` column works. It identifies the best detection for regions imaged by multiple fields (not just by multiple bands within the field). If we're just scoring bliss on one field at a time, we may not care about SDSS detections in other fields.

**Comment by jeff-regier** [comment]
[This tech report about Photo ](https://www.astro.princeton.edu/~rhl/photo-lite.pdf) says

> This operation [detection] is carried out independently in the 5 SDSS bands, and the objects detected in
> each band are also merged together.

There's also section called "Merging per-band detections" which unfortunately was never written. 

From looking the contents of the SDSS photoobj files, it appears to me that we only have access to the merged per-band detections. That may prevent us from fairly comparing BLISS (which is run on just one band) to PHOTO (which effectively uses all 5 bands). On the other hand, that makes it quite a bit more impressive that BLISS is outperforming PHOTO wrt some metrics, as BLISS only has access to one fifth of the data.

**Comment by jeff-regier** [comment]
The [table here ](http://cas.sdss.org/dr7/en/help/browser/description.asp?n=PhotoObj&t=V) also suggests that we don't have access to PHOTO's r-band detections--only to the detections from all five bands.

If we need to compare to a catalog created with just one band, we could run SExtractor on the r-band:
https://docs.astropy.org/en/stable/api/astropy.io.ascii.SExtractor.html

It's built into Astropy so it's pretty easy to use.

**Comment by ismael-mendoza** [comment]
thanks for looking intot his @jeff-regier - I think for the paper it's not essential to get comparison with only a single band. We could just state that PHOTO uses more information so it's even more impressive we are doing similarly.
