### ISSUE TITLE
AE case study: investigate double prediction in one of the SDSS blends

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#585]
Following #584, in the AE casestudy most of the blends are fixed except for one where we do a double prediction for one source. I'm curious if this is because a source centroid is close to the border of a tile iand could point to a bigger problem? 

<img width="724" alt="Screen Shot 2022-04-27 at 10 40 06 PM" src="https://user-images.githubusercontent.com/11745764/165665883-bfc20300-3ab1-45de-9f7f-cb5af4219342.png">

**Comment by dereklhansen** [comment]
This is probably due to the variational approximation to the posterior. Each tile has a marginal probability of containing a source greater than 50%, but they are likely negatively correlated (i.e. if we conditioned on a source being in one tile, the other source would have less probability of being there).

**Comment by jeff-regier** [comment]
Any chance the top right cluster is actually multiple objects? What are its coordinates?

**Comment by jeff-regier** [comment]
If this issue really is causes by nearness to a tile boundary, I don't think we need to move away from the forward KL as our variational objective, or switch to an iterative procedure. We can just divide the tiles into a black-and-white checkerboard, and condition the variational distribution for the white tiles on the variational distribution of the black tiles.

**Comment by dereklhansen** [comment]
> We can just divide the tiles into a black-and-white checkerboard, and condition the variational distribution for the white tiles on the variational distribution of the black tiles.

This should be pretty straightforward after #597. We just need to do the following:
1) Run the encoder on the entire frame
2) Mask any sources that appear in white tiles 
3) Render the image from the catalog in (2)
4) Subtract the rendered image from the true image
5) Run encoder again to get the white tiles.
6) Combine black tiles from (1) with white tiles from (5)
7) Profit

**Comment by dereklhansen** [comment]
This would work especially well with samples, but should be OK with the MAP estimation too

**Comment by ismael-mendoza** [comment]
I should mention that the probability of the lefmost tile is 0.58 (compared the 0.76 which actually contains the coadd center), so it's a bit borderline. 

The coordinates are 
```
ra: 336.7383
dec: -0.8536
```
looking at DECals, it does not appear that there are 3 galaxies there.

**Comment by jeff-regier** [comment]
@dereklhansen Would you post the coordinates of the double detections you found here when you have the chance?
