### ISSUE TITLE
Rename LocationEncoder to DetectionEncoder

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#599]
I was never in love with the name `LocationEncoder`, and `SourceEncoder` is both shorter and somewhat more descriptive (since it both detects sources in a tile and returns their locations).

**Comment by jeff-regier** [comment]
I agree `LocationEncoder` isn't great because this classes primary function is detection (and because astronomers use the term "direction", not "location"). I don't know about `SourceEncoder` though: couldn't the other encoders also be thought of as encoding sources? How about `DetectionEncoder`?
