### ISSUE TITLE
Understand max tile sources fix 

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#658]
In #657 I introduced a change that fixes the blend figure for the magnitude as a function of blendedness. The breaking changed was introduced in #650. 

But this is not satisfying, I believe there is a bug that we need to track but I need to dig more so I'm leaving it for later

![Screen Shot 2022-07-29 at 19 29 39](https://user-images.githubusercontent.com/11745764/181860297-0f08ef64-e5f3-4f1a-89e3-2e37b5d991be.png)

**Comment by dereklhansen** [comment]
As I said in my original comment back on #642, it would be best just to bump up the max sources everytime this condition is met. While this amounts to re-allocating the tensors each time, I think it's more important that the mapping between TileCatalog and FullCatalog representations is a true bijection. 

As far as I am aware, the conversion from FullCatalog to TileCatalog doesn't occur in any "hot" parts of the code anyways (i.e. during the training or prediction steps of BLISS), so I don't see much of a downside of this approach.

**Comment by dereklhansen** [comment]
From #642

| In theory the number of galaxies per tile is can go up to infinity, of course even 2 or 3 is an unlikely outcome.

I agree that this scenario may be more unstable than converting FullCatalogs from astronomical surveys (which was the original intention of the FullCatalog -> TileCatalog conversion). But, even in this simulation study, for a given FullCatalog, the number of sources per tile is bounded above by the total number of objects in the catalog, and this scenario would be quite pathological (every source in a single tile). So I'm not convinced that we should break the bijectivity of the representations just for this use case.

**Comment by ismael-mendoza** [comment]
They were two problems: 

(1) Actually, the function `to_tile_params` works fine in this context, the problem was in `UniformBrightestCenterGalsimGalaxy` that imposed a specific order in the catalog. It should remain arbitrar.  We could improve `to_tile_params` to always randomize which source it picks to be in a tile when there are multiple ones. This seems unncessary because the order of a catalog should be arbitrary in general

(2) In this context actually, I did FullCatalog -> TileCatalog -> FullCatalog without a good reason, this was the source of the issue. No reason to do a lossy transformation for this. 

I feel like (2) was the real source of the issue, so I will fix that in a PR, I can't imagine a context where (1) is a problem except when I impose an order myself.  I will also avoid that in `UniformBrightestCenterGalsimGalaxy`
