### ISSUE TITLE
Simulated Datasets outputs stars that are too big with `psf_slen` smaller than padded tile size

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#673]
Just yesterday I found what I think is a bug in the `ImageDecoder` in `decoder.py`. The stars are larger than they should be when `psf_slen` has size smaller than the padded tile. 

Using the default configuration in `sdss_galaxies/config/config.py` which uses the `psf_params_file` from the usual SDSS frame with `psf_slen=25` I get:  

<img width="279" alt="image" src="https://user-images.githubusercontent.com/11745764/186767497-2ab5fb61-c894-48bf-9b62-239b36a04e2f.png">

This is clearly wrong as the SDSS PSF from the corresponding frame has a FWHM size of approximately 1.4'' = 3.5 pixels

If I set `psf_slen=53` I get

<img width="279" alt="Screen Shot 2022-08-25 at 16 59 18" src="https://user-images.githubusercontent.com/11745764/186767745-42f99c94-fd35-47ae-9790-cf07546d0d0e.png">

In any case, I don't think `psf_slen` should affect the size of the stars in the final image but it currently does. 

I wonder if this has always been a problem or introduced recently 🤔 suggestions welcome

**Comment by ismael-mendoza** [comment]
Once this issue is resolved, we should add a test to ensure this doesn't happen again (I remember this being an issue some time back and fixing it, so I'm surprised it surfaced again)

**Comment by dereklhansen** [comment]
Does this problem occur with the old version of the decoder before the switch to `psf_decoder`?
