### ISSUE TITLE
Abstract out case_studies/**/main.py to use across different case studies

### ISSUE THREAD

**Issue by zhixiangteoh** [prob-ml/bliss#751]
Perhaps would just want to change `config_path="."`, to be parameterized by some user-defined hydra config file path, in

```
@hydra.main(config_path=".", config_name="config", version_base=None)
```

Seems like Hydra's internal definition/overriding of argparse conflicts with using argparse for this purpose, but can explore other ways.

**Comment by jeff-regier** [comment]
I agree, we shouldn't have multiple identical versions of main.py. We could create a package-wide executable called `bliss` using Poetry by modifying pyproject:
https://python-poetry.org/docs/pyproject/#scripts

Then this script would automatically be included in the path by Poetry.
