### ISSUE TITLE
remove untested code in plotting.py and catalog.py

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#793]
https://app.codecov.io/gh/prob-ml/bliss/blob/master/bliss%2Fplotting.py

https://app.codecov.io/gh/prob-ml/bliss/blob/master/bliss%2Fcatalog.py

**Comment by aakashdp6548** [comment]
`FullCatalog.apply_param_bin` is useful for computing metrics over magnitude bins. Do we want to make that a standard part of the codebase? I have it working but was focusing on the conditional metrics so haven't cleaned it up for a PR yet.

Alternatively, I can just add a test case if we want to keep it for the future but not add the binned metrics right now.

**Comment by jeff-regier** [comment]
Oh sure, let's leave it there if it's useful.
