### ISSUE TITLE
pytest warning from `test_api.py`

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#831]
pytest raises the warning below. I'm confused by it because in `testing_config.yaml` we now have `log_every_n_steps=1`, but `log_every_n_steps` appears to be set to `10` nonetheless.
```
tests/test_api.py::TestApi::test_train_on_cached_data
  /home/regier/bliss/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:1609: PossibleUserWarning: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=10). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
    rank_zero_warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by aakashdp6548** [comment]
The API uses `base_config` even for tests I think, due to some issues with how the config has to be loaded. I think Teoh was looking into how we can use `testing_config` for the API tests, which should fix the issue.

**Comment by zhixiangteoh** [comment]
> The API uses `base_config` even for tests I think, due to some issues with how the config has to be loaded. I think Teoh was looking into how we can use `testing_config` for the API tests, which should fix the issue.

Still think for now having test_api not having knowledge of testing_config is the way to go (except for CPU/GPU config)—since we want to emulate a new user's environment as much as possible.
