### ISSUE TITLE
predict_decals doesn't work with plotting

### ISSUE THREAD

**Issue by aakashdp6548** [prob-ml/bliss#859]
`predict_decals` fails when `config.predict.plot.show_plot = True`. It looks like there's two things going on:
1) `trainer.predict` returns a tile catalog, but  `plot_predict` expects a full catalog. Should just be converted in between like in `predict_sdss`.
2) `decals_plocs_from_decals` seems to return an empty tensor, which is causing problems in `predict.crop_plocs`.

Our tests right now are run without plotting enabled in the config (line 21 was added manually below) - maybe we should enable it to catch this kind of thing in the future?

![image](https://github.com/prob-ml/bliss/assets/26699876/415c49bc-8e41-4307-b835-b70bca4b3ceb)

**Comment by zhixiangteoh** [comment]
Yes, I intentionally set to false in the test I wrote in `test_predict.py` now because I’m punting this to after #853.
