### ISSUE TITLE
easier specification of the train/validate/test split

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#881]
Currently `CachedSimulatedDataset` requires us to specify the training set size in terms of the number of batches, while the validation and test sizes are specified by a list of file indices. As suggested by @zhixiangteoh and @aakashdp6548, it'd be better if we used percentages instead, e.g., 

```
train_percent_range: 0:20
val_percent_range: 80:90
test_percent_range: 90:100
```

**Comment by aakashdp6548** [comment]
Closing as duplicate of #880
