### ISSUE TITLE
torch.compile

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#905]
Looks like we'd need to upgrade to PyTorch 2.0 to use `torch.compile`:
https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html
https://lightning.ai/blog/training-compiled-pytorch-2.0-with-pytorch-lightning/

**Comment by aakashdp6548** [comment]
Trying to compile the entire `Encoder` module is causing a lot of graph breaks, particularly in metrics, plotting, and einops. Just compiling `encode_batch` works better, and seems to have a small (~20%) speedup compared to base.
```
>>> t0 = timeit.Timer(stmt="model.encode_batch(batch)", globals={"model": model, "batch": batch})
>>> t0.timeit(1000) / 1000
0.06470237739199365
>>> compiled_encode = torch.compile(model.encode_batch)
>>> t1 = timeit.Timer(stmt="fn(batch)", globals={"fn": compiled_encode, "model": model, "batch": batch})
>>> t1.timeit(1000) / 1000
0.053200025219004604
```

There's still some torch dynamo issues with compiling `encode_batch` that I want to see if we can fix/bypass before committing this.

**Comment by jeff-regier** [comment]
@aakashdp6548 Will you open a PR with whatever you have for `torch.compile`? We can work out the dynamo issues another time. A 20% speedup would be nice to have.

**Comment by aakashdp6548** [comment]
Yeah, once the UM network issues are resolved I'll make a PR.
