### ISSUE TITLE
better DC2 precision & recall for the dimmest light sources

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#973]
Figures 2 & 3 in the DC2 manuscript show BLISS being outperformed by the LSST pipeline for the dimmest light sources. We should confirm that these numbers are correct by rerunning everything. If they are correct, we should improve BLISS's image normalization for these dim light sources.

**Comment by YicunDuanUMich** [comment]
roger that

**Comment by jeff-regier** [comment]
If we need to improve BLISS's image normalization, the arcsinh transform (`torch.arcsinh`) may give us better results than log, which is what we use here:
https://github.com/prob-ml/bliss/blob/3b79b7e057777bcc504331b1fa84fd33ac3c6d31/bliss/encoder/image_normalizer.py#L93

Fiddling with some of the thresholds may help too. Currently the thresholds we use for log transforms are set here:
https://github.com/prob-ml/bliss/blob/3b79b7e057777bcc504331b1fa84fd33ac3c6d31/bliss/conf/base_config.yaml#L86

**Comment by YicunDuanUMich** [comment]
![image](https://github.com/prob-ml/bliss/assets/144750316/22f50d84-64be-463c-8659-3f5dae3dd67b)

**Comment by YicunDuanUMich** [comment]
we can now outperform lsst
